name: Hunting Open Redirect

on:
  push:
    branches: [master]

jobs:
  scan-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies & Tools
        run: |
          set -e

          # Install system deps
          sudo apt-get update
          sudo apt-get install -y wget unzip jq git golang

          # Setup pipx env
          #python3 -m pip install --upgrade pip
          #python3 -m pipx ensurepath
          export PATH="$HOME/.local/bin:$PATH"

          # Install Go-based tools
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest && sudo mv ~/go/bin/httpx /usr/bin/
          go install github.com/cybercdh/assetfinder@cybercdh && sudo mv ~/go/bin/assetfinder /usr/bin/
          go install github.com/lc/gau/v2/cmd/gau@latest && sudo mv ~/go/bin/gau /usr/bin/
          go install github.com/tomnomnom/qsreplace@latest && sudo mv ~/go/bin/qsreplace /usr/bin/
          go install github.com/tomnomnom/httprobe@latest && sudo mv ~/go/bin/httprobe /usr/bin/
          LATEST_VERSION=$(curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest | jq -r '.tag_name')
          CLEAN_VERSION=${LATEST_VERSION#v}
          wget https://github.com/projectdiscovery/nuclei/releases/download/${LATEST_VERSION}/nuclei_${CLEAN_VERSION}_linux_amd64.zip
          unzip -o nuclei_${CLEAN_VERSION}_linux_amd64.zip
          sudo mv nuclei /usr/bin/
          sudo rm -rf nuclei* *.md

          # Install Python-based tool: uro
          #pipx install uro

      - name: Recon and Hunt Open Redirect
        run: |
          mkdir -p results

          # 1. Subdomain discovery
          assetfinder squareup.com | httpx -silent -mc 200 | tee results/subdomains.txt

          # 2. Subdomain collection
          cat results/subdomains.txt | assetfinder | httpx -silent -mc 200 | tee results/subdomains-alive.txt

          # 3. Vulnerable scan
          cat results/subdomains-alive.txt | nuclei -attack-type pitchfork -rl 50 -bs 10 -c 10 -timeout 20 -retries 2 -severity low,medium,high,critical,unknown \
          | tee results/nuclei.$(date +%Y-%m-%d).txt

          # 5. Extract successful redirects
          #grep "evil.evil" results/redirect-test.txt > results/vulnerable.txt || true

      - name: Set up Git user
        run: |
          git config --global user.email "${{ secrets.EMAIL_ADDRESS }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Open Redirect Recon $(date -u)" --no-verify || echo "Nothing to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }} # atau secrets.GH_PAT kalau pakai PAT
