name: Full Recon

on:
  push:
    branches: [master]

jobs:
  recon-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies & Tools
        run: |
          set -e

          sudo apt-get update
          sudo apt-get install -y wget unzip jq git golang

          export PATH="$HOME/.local/bin:$PATH"

          # Install Go tools
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest && sudo mv ~/go/bin/httpx /usr/bin/
          go install github.com/cybercdh/assetfinder@cybercdh && sudo mv ~/go/bin/assetfinder /usr/bin/
          go install github.com/lc/gau/v2/cmd/gau@latest && sudo mv ~/go/bin/gau /usr/bin/
          go install github.com/tomnomnom/qsreplace@latest && sudo mv ~/go/bin/qsreplace /usr/bin/
          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest && sudo mv ~/go/bin/subfinder /usr/bin/
          go install github.com/projectdiscovery/dnsx/cmd/dnsx@latest && sudo mv ~/go/bin/dnsx /usr/bin/

          # Install nuclei (latest)
          LATEST_VERSION=$(curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest | jq -r '.tag_name')
          CLEAN_VERSION=${LATEST_VERSION#v}
          wget https://github.com/projectdiscovery/nuclei/releases/download/${LATEST_VERSION}/nuclei_${CLEAN_VERSION}_linux_amd64.zip
          unzip -o nuclei_${CLEAN_VERSION}_linux_amd64.zip
          sudo mv nuclei /usr/bin/
          sudo rm -rf nuclei* *.md

      - name: Recon & Vulnerability Scan
        run: |
          set -e
          mkdir -p results
      
          TARGET="unimelb.edu.au"
          DATE=$(date -u +%F-%H%M)
      
          echo "[*] Subdomain Enumeration with assetfinder & subfinder..."
          subfinder -d $TARGET -silent | assetfinder --subs-only | grep "\.${TARGET}$" > results/unimelb.txt
      
          cat results/unimelb.txt | sort -u > results/subdomains-unimelb.txt
          echo "[+] Total subdomains found: $(wc -l < results/subdomains-unimelb.txt)"
      
          echo "[*] Probing live web apps on common ports..."
          cat results/subdomains-unimelb.txt | httpx -p 80,443,8080,8443,3000,5000,8000,8888 \
            -title -status-code -tech-detect -ip -web-server -cname -location \
            -probe -follow-redirects -random-agent -fr \
            -silent -rate-limit 500 -timeout 10 -retries 3 \
            -o results/subdomains-unimelb-live.txt

          echo "[*] Checking for potential subdomain takeovers..."
          cat results/subdomains-unimelb-live.txt | grep -iE 'github|heroku|azure|fastly|zendesk|surge|unbounce|wordpress|bitbucket|ghost|desk.com' > results/takeover-candidates.txt

          echo "[*] Resolving DNS..."
          cat results/subdomains-unimelb-live.txt | awk '{print $1}' | dnsx -silent -nc -a -cname -resp -o results/unimelb-resolved.txt
      
          cat results/unimelb-resolved.txt | awk '{print $1}' | sort -u | nuclei \
            -as \
            -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36" \
            -rl 200 \
            -c 50 \
            -bs 50 \
            -timeout 10 \
            -retries 2 \
            -mhe 20 \
            -stream \
            -silent \
            -stats -si 10 \
            -sresp \
            -severity medium, high, critical, unknown \
            -t cves/,dns/,http/ \
            -o results/nuclei-unimelb-$(date +%F).txt

      - name: Set up Git Identity
        run: |
          git config --global user.email "${{ secrets.EMAIL_ADDRESS }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      - name: Commit changes
        run: |
          git add .
          git commit -m "🔎 Recon update ${{ github.sha }} at $(date -u)" --no-verify || echo "No changes to commit"

      - name: Push results
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
